### ISSUE TITLE
`Unknown log activity type:13` or `type:84` when parsing firehose log 

### ISSUE THREAD

**Issue by fukusuket** [mandiant/macos-UnifiedLogs#11]
Thank you for maintaining the tool :)
Actually, it may not be an supported data format?, but I will report it because I got following WARN.

**Describe the issue**
A warning `Unknown log activity type: 13(84)` appears when parsing files under `private/var/db/diagnostics/Persist/` files.

**Step to Reproduce**
1. `git clone https://github.com/mandiant/macos-UnifiedLogs.git` (f79a3c8905ea35091a7af8cbc303e2d22286cd4e)
2. `cd examples/unifiedlog_parser`
3. `cargo build --release`
4. `../target/release/unifiedlog_parser -l true -o out.csv`

**Expected behavior**
No warnings.

**Actual behavior**
The following two warning is displayed.
```
04:21:39 [WARN] [macos-unifiedlogs] Unknown log activity type: 13 -  0 bytes left
04:21:40 [ERROR] [macos-unifiedlogs] Parsed unknown log firehose data: Firehose { unknown_log_activity_type: 13, unknown_log_type: 160, flags: 7, format_string_location: 0, thread_id: 2251902570714803, continous_time_delta: 122829668, continous_time_delta_upper: 0, data_size: 0, firehose_activity: FirehoseActivity { unknown_activity_id: 0, unknown_sentinal: 0, pid: 0, unknown_activity_id_2: 0, unknown_sentinal_2: 0, unknown_activity_id_3: 0, unknown_sentinal_3: 0, unknown_message_string_ref: 0, unknown_pc_id: 0, firehose_formatters: FirehoseFormatters { main_exe: false, shared_cache: false, has_large_offset: 0, large_shared_cache: 0, absolute: false, uuid_relative: "", main_plugin: false, pc_style: false, main_exe_alt_index: 0 } }, firehose_non_activity: FirehoseNonActivity { unknown_activity_id: 0, unknown_sentinal: 0, private_strings_offset: 0, private_strings_size: 0, unknown_message_string_ref: 0, subsystem_value: 0, ttl_value: 0, data_ref_value: 0, unknown_pc_id: 0, firehose_formatters: FirehoseFormatters { main_exe: false, shared_cache: false, has_large_offset: 0, large_shared_cache: 0, absolute: false, uuid_relative: "", main_plugin: false, pc_style: false, main_exe_alt_index: 0 } }, firehose_loss: FirehoseLoss { start_time: 0, end_time: 0, count: 0 }, firehose_signpost: FirehoseSignpost { unknown_pc_id: 0, unknown_activity_id: 0, unknown_sentinel: 0, subsystem: 0, signpost_id: 0, signpost_name: 0, private_strings_offset: 0, private_strings_size: 0, ttl_value: 0, data_ref_value: 0, firehose_formatters: FirehoseFormatters { main_exe: false, shared_cache: false, has_large_offset: 0, large_shared_cache: 0, absolute: false, uuid_relative: "", main_plugin: false, pc_style: false, main_exe_alt_index: 0 } }, firehose_trace: FirehoseTrace { unknown_pc_id: 0, message_data: FirehoseItemData { item_info: [], backtrace_strings: [] } }, unknown_item: 0, number_items: 0, message: FirehoseItemData { item_info: [], backtrace_strings: [] } }
Parsing: /private/var/db/diagnostics/Persist/0000000000000ded.tracev3
Parsing: /private/var/db/diagnostics/Persist/0000000000000de5.tracev3
Parsing: /private/var/db/diagnostics/Persist/0000000000000dd5.tracev3
04:21:44 [WARN] [macos-unifiedlogs] Unknown log activity type: 84 -  0 bytes left
04:21:44 [ERROR] [macos-unifiedlogs] Parsed unknown log firehose data: Firehose { unknown_log_activity_type: 84, unknown_log_type: 128, flags: 5, format_string_location: 0, thread_id: 2251868778348496, continous_time_delta: 122829668, continous_time_delta_upper: 45, data_size: 0, firehose_activity: FirehoseActivity { unknown_activity_id: 0, unknown_sentinal: 0, pid: 0, unknown_activity_id_2: 0, unknown_sentinal_2: 0, unknown_activity_id_3: 0, unknown_sentinal_3: 0, unknown_message_string_ref: 0, unknown_pc_id: 0, firehose_formatters: FirehoseFormatters { main_exe: false, shared_cache: false, has_large_offset: 0, large_shared_cache: 0, absolute: false, uuid_relative: "", main_plugin: false, pc_style: false, main_exe_alt_index: 0 } }, firehose_non_activity: FirehoseNonActivity { unknown_activity_id: 0, unknown_sentinal: 0, private_strings_offset: 0, private_strings_size: 0, unknown_message_string_ref: 0, subsystem_value: 0, ttl_value: 0, data_ref_value: 0, unknown_pc_id: 0, firehose_formatters: FirehoseFormatters { main_exe: false, shared_cache: false, has_large_offset: 0, large_shared_cache: 0, absolute: false, uuid_relative: "", main_plugin: false, pc_style: false, main_exe_alt_index: 0 } }, firehose_loss: FirehoseLoss { start_time: 0, end_time: 0, count: 0 }, firehose_signpost: FirehoseSignpost { unknown_pc_id: 0, unknown_activity_id: 0, unknown_sentinel: 0, subsystem: 0, signpost_id: 0, signpost_name: 0, private_strings_offset: 0, private_strings_size: 0, ttl_value: 0, data_ref_value: 0, firehose_formatters: FirehoseFormatters { main_exe: false, shared_cache: false, has_large_offset: 0, large_shared_cache: 0, absolute: false, uuid_relative: "", main_plugin: false, pc_style: false, main_exe_alt_index: 0 } }, firehose_trace: FirehoseTrace { unknown_pc_id: 0, message_data: FirehoseItemData { item_info: [], backtrace_strings: [] } }, unknown_item: 0, number_items: 0, message: FirehoseItemData { item_info: [], backtrace_strings: [] } }
...
```

**Environment**
- OS: macOS Ventura version 13.4
- OS Language & Region : Japan
- Hard: MacBook Air(M1, 2020) , Memory 8GB, Core 8, Chip: Apple M1

**Additional context**

I checked the following document, but there is no description of `record_type = 13 (84)`, so it may have been newly added ... ?
- https://github.com/libyal/dtformats/blob/main/documentation/Apple%20Unified%20Logging%20and%20Activity%20Tracing%20formats.asciidoc#tracev3_firehose_tracepoint_record_type

Thanks once again for your great work :)
Regards,

**Comment by puffyCid** [comment]
Thanks for the issue, this looks like remnant data in the logs

Before parsing the full log the parser attempts to check the metadata of a log entry and based on the metadata parse the log type
If it cannot determine the log type it throws a warning:
`[WARN] [macos-unifiedlogs] Unknown log activity type: 13 -  0 bytes left`
This warning shows it found an unsupported log type (13), however it also prints the number of bytes left available to parse. In this case there are 0 bytes left.  
This is a strong indicator this is remnant data, because the parser has nothing left to parse, there is no data. 

After parsing the logs the parser then starts to reconstruct the log message. 
During the reconstruction process if it encounters an unsupported log type (13) it throws an ERROR because it does not know how to reconstruct this log type.  

However, since this is remnant data, theres is nothing reconstruct regardless.

Perhaps this is too much error information. Instead of logging the whole `Firehose` structure it might be better to just log the log type like the warning does?
 https://github.com/mandiant/macos-UnifiedLogs/blob/main/src/unified_log.rs#L603

Hopefully this helps explains the warnings/errors.

**Comment by fukusuket** [comment]
Thank you so much for your prompt investigation :) 
I see, I understand that the remnant data  is not able to reconstruct. ... 😵 

> Perhaps this is too much error information. Instead of logging the whole Firehose structure it might be better to just log the > log type like the warning does?

I think that the error log output as it is now is fine! 
(Because I think that it is useful to output the struct as it is in other error case investigation)

I misunderstood that the log can be reconstructed when `type=13(or84)`, so if the data cannot be reconstructed, I will close this issue.
