### ISSUE TITLE
issue parsing json produced by unifiedlog_parser_json

### ISSUE THREAD

**Issue by cvandeplas** [mandiant/macos-UnifiedLogs#16]
When trying to load some json files that `unifiedlog_parser_json` produces (such as `dataFoundInMultipleLogFiles.json`) with python a JSONDecodeError occurs.
It looks like the output of the `serde_json::to_string(&results)` ([link](https://github.com/mandiant/macos-UnifiedLogs/blob/main/examples/unifiedlog_parser_json/src/main.rs#L355)) is not always valid json.

In my case the cause was because the json structure outputted is something like:
```
["a"]["b"] 
```
This is not valid json and python does not like it. Note that some tools like `jq` are quite forgiving.
Unfortunately my Rust experience is nihil a this moment, so I'm a bit lost on how to fix this.   (and if this an issue in serde_json or here)

Thanks in advance ! 

(extra info)
ijson nicely shows the issue: 
```
In [1]: import ijson

In [2]: f =  open('parsed_data/1/logarchive/dataFoundInMultipleLogFiles.json', 'r')

In [3]: items = ijson.items(f, '')

In [4]: for item in items:
   ...:     print(item)
   ...: 
---------------------------------------------------------------------------
IncompleteJSONError                       Traceback (most recent call last)
Cell In[4], line 1
----> 1 for item in items:
      2     print(item)

IncompleteJSONError: parse error: trailing garbage
          ize": 983       }     ]   } ][   {     "subsystem": "com.app
                     (right here) ------^
```

**Comment by puffyCid** [comment]
Thanks for reporting the issue.
I see where the error is happening in the example file.

I think the easiest solution would be to output [jsonl](https://jsonlines.org/) instead of json.
Would that be an acceptable fix?

**Comment by cvandeplas** [comment]
That's an even better idea, and even brings the output closer to the native unifiedlogs parser. ( `--style ndjson`) 
I have raised a PR to implement this change.

**Comment by cvandeplas** [comment]
@puffyCid  would you be able to have a quick look at PR #18  and consider merging ?    My unit test of [another project](https://github.com/EC-DIGIT-CSIRC/sysdiagnose/pull/64) will break until this is merged ;-)  thanks a lot !
